### ISSUE TITLE
Document.asset_providers overriden on Options#initialize

### ISSUE THREAD

**Issue by opsidao** [Mange/roadie-rails#15]
Hi there!

Today I've come across what looks like a bug in the current version of roadie-rails (1.0.3), let me explain a bit. Whenever I try to inline a css link I'm hitting this exception:

```Ruby
     NoMethodError:
       undefined method `find_stylesheet' for nil:NilClass
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/provider_list.rb:41:in `block in find_stylesheet'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/provider_list.rb:40:in `each'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/provider_list.rb:40:in `find_stylesheet'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/asset_provider.rb:8:in `find_stylesheet!'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/asset_scanner.rb:84:in `read_link_element'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/asset_scanner.rb:74:in `read_stylesheet'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/asset_scanner.rb:42:in `block in extract_css'
     # ./vendor/bundle/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'
     # ./vendor/bundle/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:236:in `upto'
     # ./vendor/bundle/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:236:in `each'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/asset_scanner.rb:41:in `map'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/asset_scanner.rb:41:in `extract_css'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/document.rb:84:in `inline'
     # ./vendor/bundle/gems/roadie-3.0.0/lib/roadie/document.rb:60:in `transform'
     # ./vendor/bundle/gems/roadie-rails-1.0.2/lib/roadie/rails/mail_inliner.rb:29:in `transform_html'
     # ./vendor/bundle/gems/roadie-rails-1.0.2/lib/roadie/rails/mail_inliner.rb:21:in `improve_body'
     # ./vendor/bundle/gems/roadie-rails-1.0.2/lib/roadie/rails/mail_inliner.rb:13:in `execute'
     # ./vendor/bundle/gems/roadie-rails-1.0.2/lib/roadie/rails/mailer.rb:6:in `roadie_mail'
```

When I put some debugging into it, it turned out that the [@providers](https://github.com/Mange/roadie/blob/master/lib/roadie/provider_list.rb#L40) variables was set to `[nil]`, which logically lead to the previous error when trying to call a method on it.

After some digging around I arrived to the following piece of code in the [Options](https://github.com/Mange/roadie-rails/blob/master/lib/roadie/rails/options.rb#L40) module (this is not in the backtrace, but it seems to be the source for this problem; it gets called from [here](https://github.com/Mange/roadie-rails/blob/master/lib/roadie/rails/document_builder.rb#L6)):

```Ruby
document.asset_providers = asset_providers
```

Before this line, the `document.asset_providers` had the default `ProviderList.wrap(FilesystemProvider.new)`, the problem is that the asset_providers method, does correctly check if providers is set to something and, if it isn't, doesn't set the value for `self.asset_providers`, so self.asset_providers is nil unless you pass it through the options hash to the initializer. 

This means that the previous line simply overrides `document.asset_providers` with nil unconditionally, unless you passed an option.

My guess is that just doing something like:

```Ruby
document.asset_providers = asset_providers if asset_providers
```

should be enough, but I'm not sure if I'm missing something.... how do you see this? Did I explain myself?

**Comment by tomasc** [comment]
OK, I finally seem to have solved it.

* I needed to use `Roadie::Rails::AssetPipelineProvider` (rather than the default `FileSystemProvider` which works only with precompiled assets – therefore not in development & test). I have implemented it as a mailer interceptor like this:

```ruby
class InlineCSSInterceptor
  def self.delivering_email message
    roadie_options = ::Rails.application.config.roadie
    roadie_options.asset_providers = [ Roadie::Rails::AssetPipelineProvider.new(Rails.application.assets) ]
    Roadie::Rails::MailInliner.new(message, roadie_options).execute
  end
end

ActionMailer::Base.register_interceptor(InlineCSSInterceptor)
```

* I had to make sure that the assets do not contain digests, so that the pipeline can find them. For that, I submitted a pull request #34 .

**Comment by Mange** [comment]
`AssetPipelineProvider` should be added automatically when `Rails.application.assets` is present. As I said above, from my experimentation `Rails.application.assets` is `nil` inside engines, which is why it is never added.

Your code imply that it's present at a later time in the application lifecycle. That's interesting...

---

Your current solution isn't very good for production, however. Accessing an asset through the asset pipeline ignores precompiled assets and instead does live compilation each time an email is sent, which is slow and wasteful. I *really* don't recommend it.

Your solution also runs the risk of running Roadie twice if the mailers include either Roadie module. I recommend that you override the `roadie_options` method instead:

```ruby
class MyMailer < ActionMailer::Base
private
  def roadie_options
    super.merge(asset_providers: [Roadie::Rails::AssetPipelineProvider.new(Rails.application.assets)])
  end
  
  # Append AssetPipelineProvider instead of replacing; this makes Roadie search the filesystem first, *then* the asset pipeline
  # def roadie_options
  #   super.combine(asset_providers: [Roadie::Rails::AssetPipelineProvider.new(Rails.application.assets)])
  # end
end
```

**Comment by tomasc** [comment]
Thanks for the feedback. 

I will look into the situation with precompiled assets in production in more detail.

By the way, why is not Roadie in Rails implemented via standard ActionMailer interceptors (see #35)?

**Comment by Mange** [comment]
Because you cannot selectively activate it in specific mailers.
Interceptors are global.

tors 5 feb 2015 08:53 Tomas Celizna <notifications@github.com> skrev:

**Comment by Mange** [comment]
I'll close this while I wait for more feedback.

**Comment by ayb** [comment]
I ran into a similar issue today where my test suite was failing in a Rails 5 application because Roadie could not find the stylesheet.

For anyone that may find this -

I tried adding `config.roadie.asset_providers << Roadie::NullProvider.new` in my /environments/test.rb file in a Rails 5 application but got the error `undefined method `<<' for nil:NilClass (NoMethodError)`

So guessing Roadie has not been initialized at that point.

I was able to resolve the error by adding the following to my /config/initializers/assets.rb file:

`Rails.application.config.roadie.asset_providers << Roadie::NullProvider.new if Rails.env.test?`
