### ISSUE TITLE
Ignore fonts when displaying in GMail

### ISSUE THREAD

**Issue by Javix** [Mange/roadie-rails#64]
I can't figure out why the external fonts are not taken into account for a mail template displayed in GMail. No problems in Mail on OS X.
I reference the fonts as follows in my mai template:
```slim
    link href="https://fonts.googleapis.com/css?family=Open+Sans:bold" rel="stylesheet"
    link href="https://fonts.googleapis.com/css?family=Open+Sans:light" rel="stylesheet"
```
Any ideas on how to sole that ? Thank you.

**Comment by Mange** [comment]
Gmail, like most email clients, do not support custom webfonts. Emails
should be written like websites were made in the early 2000s: Tables for
layout, no custom fonts, no JS, etc.

You could go for progressive enhancement since there's a few number of
clients that *do* support it, but don't count on it working in most cases.

Here's one discussion of it:
http://stackoverflow.com/questions/28747848/gmail-not-showing-correct-font

I wish I could help you out more.

Den mån 15 aug. 2016 20:42Serguei Cambour <notifications@github.com> skrev:

**Comment by Javix** [comment]
@Mange Thank you very much for the feedback, I'll take a look at that.
