### ISSUE TITLE
Version 1.2.1 should be released immediately

### ISSUE THREAD

**Issue by marutosi** [Mange/roadie-rails#73]
Version 1.2.0 is installed accidentally in ruby < 2.2 without #72.

**Comment by Mange** [comment]
Is that a problem right now? I'm not using any post-2.2 features in the codebase, right?

**Comment by marutosi** [comment]
If you define gem in Gemfile:

```ruby
gem "roadie-rails", :git => 'git://github.com/Mange/roadie-rails.git',
        :ref => '17e0859195154e55c'
```

"bundle install/update" got:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    roadie-rails was resolved to 1.2.0, which depends on
      ruby (>= 2.2)

```
But in Gemfile:

```ruby
gem "roadie-rails"
```

You can install roadie-rails 1.2.0 in ruby < 2.2.
Is it very dangerous?

**Comment by ahorek** [comment]
Hi @Mange,
there is one incompatibility on windows introduced by this commit
https://github.com/Mange/roadie-rails/commit/ad745f34586a309921346c2628ccfa08dec4105a

```
gem install roadie-rails
/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:388:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)
        from /lib/ruby/site_ruby/2.1.0/rubygems/package.rb:388:in `block (2 levels) in extract_tar_gz'
        from /lib/ruby/site_ruby/2.1.0/rubygems/package/tar_reader.rb:65:in `each'
        from /lib/ruby/site_ruby/2.1.0/rubygems/package.rb:365:in `block in extract_tar_gz'
        from /lib/ruby/site_ruby/2.1.0/rubygems/package.rb:459:in `block in open_tar_gz'
        from /lib/ruby/site_ruby/2.1.0/rubygems/package.rb:456:in `wrap'
        from /lib/ruby/site_ruby/2.1.0/rubygems/package.rb:456:in `open_tar_gz'
```

the problem is symlinks are supported only on Ruby 2.2+ and also on more recent version you need administratior rights to be able to use symlinks. It worked in the previous version 1.1.1.

However symlinks are used only in your specs, is there a reason why are they included in the gem file? You can keep it in the repository, but you should remove these files from gemspec. What do you think?

**Comment by Mange** [comment]
That does sound like a real problem. Thank you for explaining it to me.
I'll take a look at this tomorrow morning!

Den tor 11 maj 2017 16:08ahorek <notifications@github.com> skrev:

**Comment by ahorek** [comment]
if you agree with not including specs in a .gem file https://github.com/Mange/roadie-rails/pull/74 and there is no other incompatibility I think you can allow older versions of ruby even if they won't be officialy supported.

```
spec.required_ruby_version = ">= 2.2"
```

**Comment by Mange** [comment]
Version 1.2.1 has been released.

**Comment by domcleal** [comment]
If #74 was merged, why is setting the minimum Ruby version to 2.2 necessary? Wasn't #74 the fix for the symlink issue on Windows?

It's a surprise to see the minimum Ruby version change in a patch release, it looks unnecessary now.

**Comment by Mange** [comment]
It's because I don't technically support Ruby < 2.2 in the 1.2 branch, and
I want to avoid accidentally breaking things for those users later IF I
start to use Ruby 2.2 features like keyword arguments.

I was just questioning the urgency if this, not the change itself.

Den fre 12 maj 2017 09:22Dominic Cleal <notifications@github.com> skrev:

**Comment by domcleal** [comment]
Ah thanks for the response, I'd missed that in the CHANGELOG.
